services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/base:bookworm
    environment:
      - SAND_API_KEY=${SAND_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ..:/workspaces/sandgarden:cached
      - /var/run/docker.sock:/var/run/docker.sock
      - ./setup.sh:/workspaces/sandgarden/setup.sh
    command: sleep infinity
    user: vscode
    init: true
    networks:
      - sandgarden_demo_network

  director:
    image: public.ecr.aws/sandgarden/sgdirector:latest
    environment:
      - SAND_LOG_LEVEL=debug
      - SAND_API_KEY=${SAND_API_KEY}
      - SAND_HOME=/.sandgarden
      - SAND_CLUSTER=demo
    ports:
      - "8987:8987"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ..:/workspaces/sandgarden
      - .sandgarden:/.sandgarden
    networks:
      - sandgarden_demo_network
  
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: tickets
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: tickets
    ports:
      - "5433:5432"
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tickets"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - sandgarden_demo_network

networks:
  sandgarden_demo_network:
    name: sandgarden_demo_network
